version: '3.0'

services:
  grafana:
    container_name: 'clevercloud-warp10-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-11.5.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/clevercloud-warp10-datasource
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - warp10
    networks:
      - warp10-net
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=clevercloud-warp10-datasource

  warp10:
    image: warp10io/warp10:3.4.1-alpine
    container_name: warp10
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - warp10-net

networks:
  warp10-net:
    driver: bridge
