name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start Grafana and Warp10 stack
        run: docker compose -f docker-compose-new.yaml up -d

      - name: Wait for Grafana to be ready
        run: |
          echo "Waiting for Grafana to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3000/login | grep -q "Grafana"; then
              echo "Grafana is up!"
              exit 0
            fi
            sleep 5
          done
          echo "Grafana did not become ready in time."
          docker compose -f docker-compose-new.yaml logs
          exit 1

      - name: Run Playwright tests
        run: npx playwright test

      - name: Shutdown services
        if: always()
        run: docker compose -f docker-compose-new.yaml down

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
